Registration revisions
ocalvet/registrationclient pull request #3
Opened 2019-03-09 21:51 UTC by carbonwheels

2019-03-10 13:26 UTC, ocalvet requested changes
When you change the IP try to get it from the environment. create-react-app uses environment variables that start with REACT_APP_ and it also lets you use it locally using a .env file

2019-03-10 13:26 UTC, ocalvet commented on src/Register/Register.js
> +    fetch("http://940.121.12.189:8080/api/registrations/", {
This IP looks weird

2019-03-10 13:26 UTC, ocalvet commented on src/Register/Register.js
> +    fetch("http://940.121.12.189:8080/api/registrations/", {
I think that 9 doesn't go there

2019-03-11 15:01 UTC, carbonwheels commented on src/Register/Register.js
> +    fetch("http://940.121.12.189:8080/api/registrations/", {
fixed ip

2019-03-11 16:57 UTC, ocalvet approved these changes

2019-03-11 16:57 UTC, merged